### ISSUE TITLE
Update expression scope

### ISSUE THREAD

**Issue by geowurster** [geowurster/pyin#41]
- `eval()` - For getting extra weird.
- `map()` - For stuff like `map(int, '2015-01-01'.split('-'))`

Do we ant to brew our own `map()` function that always returns a list, or add handling for generators before write.  Does `pmap()` already expand generators?  Should we rely on the user and maybe just check right at the very end inside the CLI?

``` console
$ cat LICENSE.txt| pyin "map(lambda x: x.lower(), line.split())"
Traceback (most recent call last):
  File "/Users/kwurster/code/benthos-pipeline/venv/bin/pyin", line 11, in <module>
    sys.exit(main())
  File "/Users/kwurster/code/benthos-pipeline/venv/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/kwurster/code/benthos-pipeline/venv/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/kwurster/code/benthos-pipeline/venv/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/kwurster/code/benthos-pipeline/venv/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/kwurster/code/benthos-pipeline/venv/lib/python2.7/site-packages/pyin/cli.py", line 96, in main
    for line in pyin.core.pmap(expressions, iterator):
  File "/Users/kwurster/code/benthos-pipeline/venv/lib/python2.7/site-packages/pyin/core.py", line 156, in pmap
    result = eval(expr, global_scope, local_scope)
  File "<string>", line 1, in <module>
NameError: name 'map' is not defined
```

**Comment by geowurster** [comment]
No reason not to just open up the global scope completely.  `map()` is easy since it is a builtin, but `eval()` takes a little more work:

``` console
$ echo "2015-01-01" | pyin "datetime.datetime.strptime(line, '%Y-%m-%d')" | pyin "eval(line)"
Traceback (most recent call last):
  File "/Users/kwurster/code/pyin/venv/bin/pyin", line 9, in <module>
    load_entry_point('pyin', 'console_scripts', 'pyin')()
  File "/Users/kwurster/code/pyin/venv/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/kwurster/code/pyin/venv/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/kwurster/code/pyin/venv/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/kwurster/code/pyin/venv/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/kwurster/code/pyin/pyin/cli.py", line 110, in main
    for line in pyin.core.pmap(expressions, iterable):
  File "/Users/kwurster/code/pyin/pyin/core.py", line 169, in pmap
    result = eval(expr, {}, local_scope)
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
NameError: name 'datetime' is not defined
```

Tricking `pyin` into importing `datetime` works:

``` console
$ echo "2015-01-01" | pyin "datetime.datetime.strptime(line, '%Y-%m-%d')" | pyin "line != datetime.datetime" "eval(line)"
datetime.datetime(2015, 1, 1, 0, 0)
```

Not worth figuring out the right solution until there's a real use case.  Maybe a `--module` flag to pre-import stuff.
