### ISSUE TITLE
Suppress IOError when piping to another process that does not fully consume pyin's output

### ISSUE THREAD

**Issue by geowurster** [geowurster/pyin#52]
``` console
$ cat LICENSE.txt| pyin line | head -1
New BSD License
Traceback (most recent call last):
  File "/Users/kwurster/Library/Python/2.7/bin/pyin", line 9, in <module>
    load_entry_point('pyin', 'console_scripts', 'pyin')()
  File "/Users/kwurster/Library/Python/2.7/lib/python/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/kwurster/Library/Python/2.7/lib/python/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/kwurster/Library/Python/2.7/lib/python/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/kwurster/Library/Python/2.7/lib/python/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/kwurster/code/pyin/pyin/cli.py", line 122, in main
    outfile.write(line)
  File "/Users/kwurster/Library/Python/2.7/lib/python/site-packages/click/_compat.py", line 63, in write
    return io.TextIOWrapper.write(self, x)
IOError: [Errno 32] Broken pipe
```

Looks like this is only a problem when reading from `stdin`.

``` console
$ pyin -i LICENSE.txt line | head -1
New BSD License
```

**Comment by geowurster** [comment]
Also this is fixed in Python 3:

``` console
$ python --version && cat LICENSE.txt| pyin line | head -1
Python 3.5.1
New BSD License
```
